=== obalyaev/ship-sdk/schemata/guest-stay-list-result-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "guestStayListResult",
  "description": "A guestStayListResult object is a result object with additional fields to indicate the result of processing a guest-stay list message.",
  "type": "object",
  "properties": {
    "message": {
      "description": "Description of the result",
      "type": "string"
    },
    "field": {
      "description": "JSON path identifying the SHIP field to which the result pertains",
      "type": "string"
    },
    "summary": {
      "description": "Summary of the guest-stay list result",
      "$ref": "#/definitions/summary"
    },
    "errors": {
      "description": "Errors generated by the processing of the guest-stay list",
      "type": "array",
      "items": {
        "$ref": "result-schema.json#"
      }
    },
    "warnings": {
      "description": "Warnings generated by the processing of the guest-stay list",
      "type": "array",
      "items": {
        "$ref": "result-schema.json#"
      }
    }
  },
  "additionalProperties": false,
  "definitions": {
    "summary": {
      "description": "Summary of the guest-stay list result",
      "type": "object",
      "required": [
        "successCount",
        "errorCount",
        "totalCount"
      ],
      "properties": {
        "successCount": {
          "description": "Number of guestStays successfully processed",
          "type": "integer"
        },
        "errorCount": {
          "description": "Number of guestStays that failed to process",
          "type": "integer"
        },
        "totalCount": {
          "description": "Total number of guestStays processed",
          "type": "integer"
        }
      },
      "additionalProperties": false
    }
  }
}

=== obalyaev/ship-sdk/samples/guest-stay-list-results/guest-stay-list-result-full.json
{
  "message": "Some guest-stay transformations failed",
  "field": "$",
  "summary": {
    "successCount": 1,
    "errorCount": 1,
    "totalCount": 2
  },
  "errors": [
    {
      "message": "is required",
      "field": "$.[1].profiles[0].lastName"
    }
  ],
  "warnings": [
    {
      "message": "is recommended",
      "field": "$.[0].reservationSource"
    },
    {
      "message": "is recommended",
      "field": "$.[0].profiles[0].primaryLanguage"
    },
    {
      "message": "is recommended",
      "field": "$.[1].profiles[0].postalAddresses[0].address1"
    },
    {
      "message": "is recommended",
      "field": "$.[1].profiles[0].postalAddresses[0].city"
    }
  ]
}
