=== obalyaev/ship-sdk/schemata/guest-stay-result-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "guestStayResult",
  "description": "A guestStayResult object is a result object with additional fields to indicate the result of processing a guest-stay message.",
  "type": "object",
  "properties": {
    "status": {
      "description": "Status code of the result",
      "type": "string",
      "enum": ["NEW", "SUCCESS", "WARNING", "FAILED", "MISSING", "DELETE"]
    },
    "message": {
      "description": "Description of the result",
      "type": "string"
    },
    "sourceField": {
      "description": "If the incoming message was transformed, this identifies the field of the incoming message to which the result pertains",
      "type": "string"
    },
    "sourceValue": {
      "description": "If the incoming message was transformed, the original value in the incoming message to which the result pertains",
      "type": "string"
    },
    "field": {
      "description": "JSON pointer identifying the SHIP field to which the result pertains",
      "type": "string"
    },
    "guestStay": {
      "description": "The guestStay object produced by processing the incoming message. May be invalid, check errors first.",
      "$ref": "guest-stay-schema.json#"
    },
    "errors": {
      "description": "Errors generated by the processing of the guest-stay",
      "type": "array",
      "items": {
        "$ref": "result-schema.json#"
      }
    },
    "warnings": {
      "description": "Warnings generated by the processing of the guest-stay",
      "type": "array",
      "items": {
        "$ref": "result-schema.json#"
      }
    }
  },
  "additionalProperties": false
}

=== obalyaev/ship-sdk/samples/guest-stay-results/guest-stay-result-full.json
{
  "status": "FAILED",
  "message": "Transformation to guest-stay failed with multiple causes:\n    guestStay#/totalDepositRequired/value Transformation failed: Not a number\n    guestStay#/totalLuggageRevenue/amountBeforeTax/value Transformation failed: Not a number\n",
  "sourceField": "row 0",
  "sourceValue": "\"NOT AVAILABLE\",\"1194.0000\",\"1194.0000\",\"NULL\",\"NULL\",\".\",,,,\"CRO\",,,\"0\",\"1\",\"100.99\",\"CC\",\"EN\",,,,,\"TREE\",\"N\",,,,,,\"PLAT\"",
  "field": "guestStay#",
  "guestStay": {
    "action": "CHECKOUT",
    "property": "AVERTINE",
    "confirmationCode": "38000",
    "statusCode": "CHECKEDOUT",
    "checkinDate": "2007-07-19",
    "checkoutDate": "2007-07-22",
    "roomNumber": "123",
    "roomType": "KING",
    "profiles": [
      {
        "action": "ADD",
        "property": "AVERTINE",
        "profileId": "28002",
        "profileType": "GUEST",
        "firstName": "Contact",
        "lastName": "Sample",
        "emailAddresses": [
          {
            "emailAddress": "sample@mailinator.com",
            "primary": true
          }
        ]
      }
    ]
  },
  "errors": [
    {
      "status": "FAILED",
      "message": "Transformation failed: Not a number",
      "sourceField": "cell 7",
      "sourceValue": "",
      "field": "guestStay#/totalDepositRequired/value"
    },
    {
      "status": "FAILED",
      "message": "Transformation failed: Not a number",
      "sourceField": "cell 8",
      "sourceValue": "",
      "field": "guestStay#/totalLuggageRevenue/amountBeforeTax/value"
    }
  ],
  "warnings": [
    {
      "status": "FAILED",
      "message": "Transformation failed: Invalid format: \"NOT AVAILABLE\"",
      "sourceField": "cell 0",
      "sourceValue": "NOT AVAILABLE",
      "field": "guestStay#/actualCheckoutDate"
    }
  ]
}

=== obalyaev/ship-sdk/samples/guest-stay-results/guest-stay-result-novalue.json
{
  "status": "FAILED",
  "message": "Transformation to guest-stay failed with multiple causes:\n    guestStay#/totalDepositRequired/value Transformation failed: Not a number\n    guestStay#/totalLuggageRevenue/amountBeforeTax/value Transformation failed: Not a number\n",
  "sourceField": "row 0",
  "sourceValue": "\"NOT AVAILABLE\",\"1194.0000\",\"1194.0000\",\"NULL\",\"NULL\",\".\",,,,\"CRO\",,,\"0\",\"1\",\"100.99\",\"CC\",\"EN\",,,,,\"TREE\",\"N\",,,,,,\"PLAT\"",
  "field": "guestStay#",
  "errors": [
    {
      "status": "FAILED",
      "message": "Transformation failed: Not a number",
      "sourceField": "cell 7",
      "sourceValue": "",
      "field": "guestStay#/totalDepositRequired/value"
    },
    {
      "status": "FAILED",
      "message": "Transformation failed: Not a number",
      "sourceField": "cell 8",
      "sourceValue": "",
      "field": "guestStay#/totalLuggageRevenue/amountBeforeTax/value"
    }
  ],
  "warnings": [
    {
      "status": "FAILED",
      "message": "Transformation failed: Invalid format: \"NOT AVAILABLE\"",
      "sourceField": "cell 0",
      "sourceValue": "NOT AVAILABLE",
      "field": "guestStay#/actualCheckoutDate"
    }
  ]
}
