=== obalyaev/ship-sdk/schemata/profile-result-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "profileResult",
  "description": "A profileResult object is a result object with additional fields to indicate the result of processing a profile message.",
  "type": "object",
  "properties": {
    "status": {
      "description": "Status code of the result",
      "type": "string",
      "enum": ["NEW", "SUCCESS", "WARNING", "FAILED", "MISSING", "DELETE"]
    },
    "message": {
      "description": "Description of the result",
      "type": "string"
    },
    "sourceField": {
      "description": "If the incoming message was transformed, this identifies the field of the incoming message to which the result pertains",
      "type": "string"
    },
    "sourceValue": {
      "description": "If the incoming message was transformed, the original value in the incoming message to which the result pertains",
      "type": "string"
    },
    "field": {
      "description": "JSON pointer identifying the SHIP field to which the result pertains",
      "type": "string"
    },
    "profile": {
      "description": "The profile object produced by processing the incoming message. May be invalid, check errors first.",
      "$ref": "profile-schema.json#"
    },
    "errors": {
      "description": "Errors generated by the processing of the profile",
      "type": "array",
      "items": {
        "$ref": "result-schema.json#"
      }
    },
    "warnings": {
      "description": "Warnings generated by the processing of the profile",
      "type": "array",
      "items": {
        "$ref": "result-schema.json#"
      }
    }
  },
  "additionalProperties": false
}

=== obalyaev/ship-sdk/samples/profile-results/profile-result-success.json
{
  "status": "SUCCESS",
  "sourceField": "row 0",
  "field": "profile#",
  "profile": {
    "action": "ADD",
    "property": "d5e974f4-41e9-4a33-9290-eed5a6086597",
    "interfaceType": "FILE",
    "remoteSystemName": "b30b3a97-5b6d-4199-a35c-fcece539504f",
    "profileType": "GUEST",
    "firstName": "Mango000001",
    "lastName": "Tango000001",
    "emailAddresses": [
      {
        "emailAddress": "Mango000001@mailbox.revinate.net",
        "primary": true
      }
    ]
  }
}
