=== obalyaev/ship-sdk/schemata/profile-list-result-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "profileListResult",
  "description": "A profileListResult object is a result object with additional fields to indicate the result of processing a profile list message.",
  "type": "object",
  "properties": {
    "status": {
      "description": "Status code of the result",
      "type": "string",
      "enum": ["NEW", "SUCCESS", "WARNING", "FAILED", "MISSING", "DELETE"]
    },
    "message": {
      "description": "Description of the result",
      "type": "string"
    },
    "sourceField": {
      "description": "If the incoming message was transformed, this identifies the field of the incoming message to which the result pertains",
      "type": "string"
    },
    "sourceValue": {
      "description": "If the incoming message was transformed, the original value in the incoming message to which the result pertains",
      "type": "string"
    },
    "field": {
      "description": "JSON pointer identifying the SHIP field to which the result pertains",
      "type": "string"
    },
    "summary": {
      "description": "Summary of the profile list result",
      "$ref": "#/definitions/summary"
    },
    "profiles": {
      "description": "Profile results produced by processing the incoming message",
      "type": "array",
      "items": {
        "$ref": "profile-result-schema.json#"
      }
    },
    "errors": {
      "description": "Errors generated by the processing of the guest-stay list. Deprecated, use guestStays instead.",
      "type": "array",
      "items": {
        "$ref": "result-schema.json#"
      }
    },
    "warnings": {
      "description": "Warnings generated by the processing of the guest-stay list. Deprecated, use guestStays instead.",
      "type": "array",
      "items": {
        "$ref": "result-schema.json#"
      }
    }
  },
  "additionalProperties": false,
  "definitions": {
    "summary": {
      "description": "Summary of the profile list result",
      "type": "object",
      "required": [
        "successCount",
        "errorCount",
        "totalCount"
      ],
      "properties": {
        "successCount": {
          "description": "Number of profiles successfully processed",
          "type": "integer"
        },
        "errorCount": {
          "description": "Number of profiles that failed to process",
          "type": "integer"
        },
        "totalCount": {
          "description": "Total number of profiles processed",
          "type": "integer"
        }
      },
      "additionalProperties": false
    }
  }
}

=== obalyaev/ship-sdk/samples/profile-list-results/profile-list-result-full.json
{
  "status": "FAILED",
  "message": "All profile transformations failed",
  "sourceField": "table",
  "field": "profileList#",
  "summary": {
    "successCount": 0,
    "errorCount": 1,
    "totalCount": 1
  },
  "profiles": [
    {
      "status": "FAILED",
      "message": "Transformation to profile failed with multiple causes:\n    profile#/emailAddresses/0/primary Transformation failed: Could not parse \"not_a_boolean\"\n",
      "sourceField": "row 0",
      "sourceValue": "\"Mango000001\",\"Tango000001\",\"Mango000001@mailbox.revinate.net\",\"not_a_boolean\",\"not_a_gender\"",
      "field": "profile#",
      "profile": {
        "action": "ADD",
        "property": "d5e974f4-41e9-4a33-9290-eed5a6086597",
        "interfaceType": "FILE",
        "remoteSystemName": "b30b3a97-5b6d-4199-a35c-fcece539504f",
        "profileType": "GUEST",
        "firstName": "Mango000001",
        "lastName": "Tango000001",
        "emailAddresses": []
      },
      "errors": [
        {
          "status": "FAILED",
          "message": "Transformation failed: Could not parse \"not_a_boolean\"",
          "sourceField": "cell 3",
          "sourceValue": "not_a_boolean",
          "field": "profile#/emailAddresses/0/primary"
        }
      ],
      "warnings": [
        {
          "status": "FAILED",
          "message": "Transformation failed: \"not_a_gender\" is not a valid Gender",
          "sourceField": "cell 4",
          "sourceValue": "not_a_gender",
          "field": "profile#/gender"
        }
      ]
    }
  ]
}
